CREATE TABLE IF NOT EXISTS "quiz_room" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"room_nd" INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "object_to_repair" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(155) NOT NULL,
	"image" VARCHAR(255) NOT NULL,
	"mission" TEXT NOT NULL,
	"answer1" VARCHAR(255),
	"answer2" VARCHAR(255),
	"answer3" VARCHAR(255),
	"good_answer" VARCHAR(255) NOT NULL,
	"challenge_type" VARCHAR(255),
	"precision" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "questions_to_ask" (
	"quiz_room_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"object_to_sort_id" INTEGER NOT NULL,
	"object_to_repair_id" INTEGER NOT NULL,
	PRIMARY KEY("quiz_room_id")
);




CREATE TABLE IF NOT EXISTS "object_to_sort" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(155) NOT NULL,
	"image" VARCHAR(255) NOT NULL,
	"mission" TEXT NOT NULL,
	"answer1" VARCHAR(255),
	"answer2" VARCHAR(255),
	"answer3" VARCHAR(255),
	"good_answer" VARCHAR(255) NOT NULL,
	"challenge_type" VARCHAR(255),
	"precision" TEXT,
	PRIMARY KEY("id")
);



ALTER TABLE "questions_to_ask"
ADD FOREIGN KEY("object_to_sort_id") REFERENCES "object_to_repair"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "questions_to_ask"
ADD FOREIGN KEY("quiz_room_id") REFERENCES "quiz_room"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "questions_to_ask"
ADD FOREIGN KEY("object_to_repair_id") REFERENCES "object_to_sort"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;